apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gatewayName }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"

spec:
  selector:
    istio: {{ .Values.istio.ingressGatewayName }}
  servers:
    - port:
        number: {{ .Values.istio.ingressGatewayPort }}
        name: http2
        protocol: HTTP2
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eric-nef-virtualservice
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"

spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.istio.gatewayName }}
  http:
    - match:
        - uri:
            regex: "^/3gpp-traffic-influence/v1/[0-9]*/notification/.*$"
      route:
        - destination:
            host: {{ .Values.global.prefix }}-{{ .Values.services.name_nef_traffic_influence }}
            port:
              number: 5081
    - match:
        - uri:
            prefix: /3gpp-traffic-influence
      route:
        - destination:
            host: {{ .Values.global.prefix }}-{{ .Values.services.name_nef_traffic_influence }}
            port:
              number: 5080
    - match:
        - uri:
            prefix: /3gpp-monitoring-event
        - uri:
            prefix: /nef-notifications
      route:
        - destination:
            host: {{ .Values.global.prefix }}-{{ .Values.services.name_nef_evex }}
            port:
              number: 80
    - match:
        - uri:
            prefix: /3gpp-bdt
      route:
        - destination:
            host: {{ .Values.global.prefix }}-{{ .Values.services.name_nef_bdt }}
            port:
              number: 80
    - match:
        - uri:
            prefix: /3gpp-chargeable-party
        - uri:
            prefix: /cp/
      route:
        - destination:
            host: {{ .Values.global.prefix }}-{{ .Values.services.name_nef_cp }}
            port:
              number: 80
