eric-nrf-common:
  eric-data-kvdb-ag:
    replicas:
      locator: 2
      server: 2

    persistence:
      data:
        # Set to false if you do not wish to use persistent storage for database data
        enabled: true
        accessMode: ReadWriteOnce
      backup:
        # Set the enabled flag to false in case you do not wish to use this type of storage.
        # Keep in mind that this will prevent you from using B&R functionality
        enabled: false
        accessMode: ReadWriteOnce
        locator:
          allocation: 2Gi
        server:
          allocation: 4Gi
        adminMgr:
          allocation: 8Gi

    jvmHeap:
      initDepend: 100m
      database:
        locator: 3200m
        server: 3200m
      monitor: 384m
      jmxExporter: 384m
      adminMgr: 512m

    jvmOptions:
      initDepend:
      database:
        locator:
        - '"-XX:+UseG1GC"'
        - '"-XX:MaxGCPauseMillis=10"'
        - '"-Xlog:gc:file=srvgc.log"'
        server:
        - '"-XX:+UseG1GC"'
        - '"-XX:MaxGCPauseMillis=10"'
        - '"-Xlog:gc:file=srvgc.log"'
        - '"-Dgeode.feature-protobuf-protocol=true"'
      monitor:
      jmxExporter:

    requests:
      initDepend:
        cpu: 200m
        memory: 128Mi
      initDb:
        cpu: 200m
        memory: 128Mi
      database:
        locator:
          cpu: 2000m
          memory: 4Gi
        server:
          cpu: 2000m
          memory: 4Gi
      monitor:
        cpu: 500m
        memory: 650Mi
      jmxExporter:
        cpu: 200m
        memory: 512Mi
      adminMgr:
        cpu: 1000m
        memory: 750Mi

    limits:
      initDepend:
        cpu: 200m
        memory: 128Mi
      initDb:
        cpu: 200m
        memory: 128Mi
      database:
        locator:
          cpu: 2000m
          memory: 4Gi
        server:
          cpu: 2000m
          memory: 4Gi
      monitor:
        cpu: 500m
        memory: 650Mi
      jmxExporter:
        cpu: 200m
        memory: 512Mi
      adminMgr:
        cpu: 2000m
        memory: 750Mi

    probing:
      readiness:
        initialDelaySeconds: 50
      liveness:
        monitor:
          initialDelaySeconds: 60
        database:
          initialDelaySeconds: 60
        jmxExporter:
          initialDelaySeconds: 60

eric-nrf-management:
  mgmt:  
    replicacount: 2
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 1000Mi
        cpu: 200m

  notification:
    replicacount: 2
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 1000Mi
        cpu: 200m 
        
  dbproxy:
    resources:
      requests:
        memory: 4000Mi
        cpu: 250m
      limits:
        memory: 4000Mi
        cpu: 250m  
        
eric-nrf-discovery:
  disc:
    replicacount: 2
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 500Mi
        cpu: 250m  
        
  dbproxy:
    resources:
      requests:
        memory: 1000Mi
        cpu: 500m
      limits:
        memory: 1000Mi
        cpu: 500m 

eric-nrf-accesstoken:
  accesstoken:
    replicacount: 2
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 500Mi
        cpu: 250m

  dbproxy:
    resources:
      requests:
        memory: 1000Mi
        cpu: 250m
      limits:
        memory: 1000Mi
        cpu: 250m

eric-nrf-provision:
  prov:
    replicacount: 2
    resources:
      requests:
        memory: 100Mi 
        cpu: 100m
      limits:
        memory: 200Mi 
        cpu: 200m

  dbproxy:
    resources:
      requests:
        memory: 300Mi
        cpu: 50m
      limits:
        memory: 600Mi
        cpu: 100m
 
