apiVersion: v1
kind: ConfigMap
data:
{{ (.Files.Glob "config/schema/nfProfile.json").AsConfig | indent 2 }}
{{ (.Files.Glob "config/schema/patchDocument.json").AsConfig | indent 2 }}
{{ (.Files.Glob "config/schema/subscriptionData.json").AsConfig | indent 2 }}
{{ (.Files.Glob "config/schema/subscriptionPatch.json").AsConfig | indent 2 }}
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.nrf_schema.jsonschema.configmap.name }}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
data:
{{ (.Files.Glob "config/dbproxy/attributes.json").AsConfig | indent 2 }}
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.global.dbproxy.configmap.name }}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.global.db.multisite.configmap.name }}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
data:
  eric-nrf-multiSite-conf.json: |-
    {
      "HeartbeatTime": 3,
      "MonitorTime": 5,
      "ExpireTime": 10,
      "Enabled": {{ index .Values "eric-data-kvdb-ag" "multiSite" "enabled" }}
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.global.db.info.configmap.name }}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
data:
  eric-nrf-dbinfo-conf.json: |
    {
        "locator-server-name": "{{ index .Values "eric-data-kvdb-ag" "nameOverride" }}-locator",
        "region-names": "ericsson-nrf-nrfaddresses;ericsson-nrf-nfprofiles;ericsson-nrf-nfhelper;ericsson-nrf-subscriptions;ericsson-nrf-groupprofiles;ericsson-nrf-imsiprefixprofiles;ericsson-nrf-nrfprofiles;ericsson-nrf-gpsiprofiles;ericsson-nrf-gpsiprefixprofiles;ericsson-nrf-cachenfprofiles;ericsson-nrf-multisiteinfo;ericsson-nrf-witnessinfo;ericsson-nrf-distributedlock;ericsson-nrf-regionnfinfo",
        "locator-server-port": {{ index .Values "eric-data-kvdb-ag" "servicePorts" "kvdbAgLocator" | quote }}
    }
---
{{- if empty .Values.global.resourcePrefix }}
apiVersion: v1
kind: ConfigMap
data:
{{ (.Files.Glob "config/logconfig/logControl.json").AsConfig | indent 2 }}
metadata:
  name: {{ template "eric-nrf-common.name" . }}-log-config
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
{{- end }}
