apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.rbac.pod_role}}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["networking.istio.io"]
  resources: ["serviceentries", "destinationrules"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.rbac.pod_rolebinding}}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.rbac.pod_account }}
roleRef:
  kind: Role
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.rbac.pod_role}}
  apiGroup: rbac.authorization.k8s.io
