apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-nrf-common.name" . }}-{{ .Values.rbac.pod_account }}
  labels:
{{- include "eric-nrf-common.labels" . | indent 4 }}
  annotations:
{{- include "eric-nrf-common.product-info" . | indent 4 }}