apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.nrfCommon.cmHook.postDelete.name }}
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Values.nrfCommon.cmHook.postDelete.name }}
      labels:
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.nrfCommon.cmHook.postDelete.name }}
        image: {{ .Values.global.imageCredentials.repository }}/{{ .Values.nrfCommon.image.name }}:{{ .Values.nrfCommon.image.tag }}
        imagePullPolicy: {{ .Values.nrfCommon.image.pullPolicy }}
        command:
        - /bin/delete-cm-schema-conf.sh
        env:
        - name: POST_HOOK_DELETE_ENABLED
          value: {{ .Values.nrfCommon.cmHook.postDelete.enabled }}
        - name: CM_SERVICE
          value: {{ .Values.global.cmproxy.cmm_service }}
        - name: CM_SCHEMA_NAME
          value: {{ .Values.global.cmproxy.cmm_config_schema_prefix_name }}
