# ########################################################################### #
# Deployment Tags, select which 5g@udm service would like to deploy
# ########################################################################### #
tags:
  eric-adp-common: false
  eric-data-document-database-pg: true
  eric-cm-mediator: true
  eric-pm-server: true
  eric-pm-bulk-reporter: true
  eric-data-coordinator-zk: true
  eric-data-message-bus-kf: true
  eric-log-shipper: true
  eric-data-search-engine: true
  eric-data-visualizer-kb: false
  eric-fh-alarm-handler: true
  eric-fh-snmp-alarm-provider: true
  eric-cm-yang-provider: true
  eric-data-search-engine-curator: false
  eric-odca-diagnostic-data-collector: false
  eric-log-transformer: false
  eric-sec-access-mgmt: false
  eric-sec-ldap-server: false
  eric-ctrl-bro: false 

# ########################################################################### #
# Custom ADP Generic Services Values (Overwrite the default values)
# ########################################################################### #

eric-pm-server:
  server:
    persistentVolume:
      enabled: false

eric-fh-alarm-handler:
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: false
  backend:
    hostname: "eric-data-document-database-pg"
    dbname: adp_gs_cm
  alarmhandler:
    jobs:
      createAHTopics: false
  resources:
    alarmhandler:
      requests:
        cpu: "100m"

eric-data-document-database-pg:
  persistence:
    storageClassName: erikube-rbd
    size: 100Mi
    backup:
      enabled: false
  highAvailability:
    synchronousModeEnabled: false
    replicaCount: 1
  metrics.enabled: false

eric-data-coordinator-zk:
  replicas: 2
  resources:
    datacoordinatorzk:
      requests:
        cpu: '300m'
        memory: 200Mi
  persistantVolumeClaim:
    storage: 200Mi
    storageClassName: erikube-rbd

eric-data-message-bus-kf:
  resources:
    messagebuskf:
      requests:
        cpu: 500m
        memory: "200Mi"
  replicas: 2
  persistentVolumeClaim:
    storageClassName: erikube-rbd
    storage: 200Mi
  jmx:
    enabled: false
  configurationOverrides:
    offsets.topic.replication.factor: 1
    offsets.topic.num.partitions: 3
    default.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    transaction.state.log.num.partitions: 1
    min.insync.replicas: 1

eric-cm-mediator:
  replicaCount: 1
  service:
    name: eric-cm-mediator
    type: NodePort
  backend:
    hostname: eric-data-document-database-pg
  ingress:
    host: eric-cm-mediator.localhost
  kafka:
    hostname: eric-data-message-bus-kf
    port: 9092
  resources:
    cm-mediator:
      requests:
        cpu: "200m"

eric-pm-bulk-reporter:
  env:
    nodeName: minikube
    nodeType: 5G_UDM
  service:
    servicePort: 9022
    type: NodePort
  persistentVolumeClaim:
    enabled: true
    storageClassName: erikube-rbd

eric-data-search-engine:
  replicas:
    ingest: 1
    master: 1
    data: 1
  master:
    minMasters: 1
  resources:
    ingest:
      limits:
        cpu: "100m"
        memory: "300Mi"
      requests:
        cpu: "100m"
        memory: "300Mi"
    master:
      limits:
        cpu: "100m"
        memory: "800Mi"
      requests:
        cpu: "100m"
        memory: "800Mi"
    data:
      limits:
        cpu: "100m"
        memory: "200Mi"
      requests:
        cpu: "100m"
        memory: "200Mi"
  jvmHeap:
    data: "256m"
  data:
    storageAllocation: 250Mi
  persistence:
    storageClass: erikube-rbd

eric-data-visualizer-kb:
  replicaCount: 1
  service:
    type: NodePort
  resources:
    limits:
      memory: 250Mi
      cpu: 500m
    requests:
      memory: 100Mi
      cpu: 100m

eric-cm-yang-provider:
  service:
    type: NodePort
  ingress:
    enabled: false
  persistentVolumeClaim:
    enabled: false
  resources:
    confd:
      requests:
        cpu: 150m
      limits:
        memory: 500Mi
        cpu: 200m
    cpa:
      limits:
        memory: 250Mi
        cpu: 100m
    ss:
      limits:
        memory: 250Mi
        cpu: 100m
    notif:
      limits:
        memory: 250Mi
        cpu: 100m
    yang:
      limits:
        memory: 250Mi
        cpu: 100m
    ypint:
      limits:
        memory: 250Mi
        cpu: 100m
    validator:
      limits:
        memory: 250Mi
        cpu: 100m

eric-log-transformer:
  resources:
    logtransformer:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 500Mi

eric-ctrl-bro:
  resources:
    backupAndRestore:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
  persistentVolumeClaim:
    storageClassName: erikube-rbd
    storage: 300m

eric-sec-access-mgmt:
  resources:
    iam:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "300m"

eric-sec-ldap-server:
  resources:
    ldap:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  persistence:
    storageClassName: erikube-rbd

