apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.nrfagentCommon.cmHook.postDelete.name }}
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Values.nrfagentCommon.cmHook.postDelete.name }}
      labels:
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.nrfagentCommon.cmHook.postDelete.name }}
        image: {{ .Values.global.imageCredentials.repository }}/{{ .Values.nrfagentCommon.image.name }}:{{ .Values.nrfagentCommon.image.tag }}
        imagePullPolicy: {{ .Values.nrfagentCommon.image.pullPolicy }}
        command:
        - /etc/nrfagent/scripts/nrfagent-delete-cm-schema-conf.sh
        env:
        - name: POST_HOOK_DELETE_ENABLED
          value: {{ .Values.nrfagentCommon.cmHook.postDelete.enabled }}
        - name: CM_SERVICE
          value: {{ .Values.global.cm_uri_prefix }}
        - name: CM_SCHEMA_NAME
          value: {{ .Values.global.cm_config_schema_prefix_name }}
        - name: CM_LOG_NAME
          value: {{ .Values.global.cm_config_log_name }}
