apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "eric-nef-nf-registration.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "eric-nef-nf-registration.name" . }}
    app.kubernetes.io/version: {{ include "eric-nef-nf-registration.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "eric-nef-nf-registration.chart" . }}
  annotations:
        {{- include "eric-nef-nf-registration.product-info" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-nef-nf-registration.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
          {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml .Values.updateStrategy.rollingUpdate | indent 6 }}
        {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eric-nef-nf-registration.name" . }}
        app.kubernetes.io/version: {{ include "eric-nef-nf-registration.version" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ template "eric-nef-nf-registration.chart" . }}
      annotations:
          {{- include "eric-nef-nf-registration.product-info" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: "In"
                      values:
                        - {{ template "eric-nef-nf-registration.name" . }}
                topologyKey: "kubernetes.io/hostname"
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if (include "eric-nef-nf-registration.pullSecrets" .) }}
      imagePullSecrets:
        - name: {{ template "eric-nef-nf-registration.pullSecrets" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "eric-nef-nf-registration.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ index .Values "images" "nfReg" "name" }}:{{ index .Values "images" "nfReg" "tag" }}
          imagePullPolicy: {{ required "A valid .Values.imageCredentials.imagePullPolicy entry is required!" .Values.imageCredentials.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "eric-nef-nf-registration.name" . }}-config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources.nfReg | indent 12 }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone }}
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}
            - name: LOG_CTL_FILE_PATH
              value: {{ .Values.global.logControl.monitorFileDir }}
            - name: LOG_CTL_FILE_NAME
              value: {{ .Values.global.logControl.monitorFilename }}
            - name: LOG_FORMAT_SRV_ID
              value: "eric-nef-nrfintegration"
            - name: LOG_FORMAT_NET_FUNC
              value: "NEF"
            - name: LOG_CTL_DEFAULT_LEVEL
              value: {{ .Values.logging.level }}
          volumeMounts:
            - name: cces-log-config-volume
              mountPath: {{ .Values.global.logControl.monitorFileDir }}
      volumes:
        - name: cces-log-config-volume
          configMap:
            name: {{ .Values.global.logControl.configmapName }}
            defaultMode: 0777
