replicacount:
  nrfagent_ntf: 1
  nrfagent_disc: 2

hpa:
  enabled: true
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

namespace:
  name_nrfagent: default
  name_istio: istio-system

service:
  name_nrfagent_ntf: nrf-notify-agent
  name_nrfagent_disc: nrf-discovery-agent
  name_nrfagent_reg: nrf-register-agent
  cm_check_enable: "'true'"

liveness:
  initialDelay: 120
  period: 60

readiness:
  initialDelay: 5
  period: 4

image:
  name: nrfagentdisc
  tag: dev

imageCredentials:
  pullPolicy: IfNotPresent

args:
  maxstreams: "'600'"
  test_maxstreams: "'8000'"
  loglevel: "'5'"
  confFile: /app/nrfagent/conf/nrfagent_conf.json

serviceport:
  ntf_h1_withouttls: 3011
  ntf_h2_withtls: 3012
  ntf_h2_withouttls: 3013
  disc_h1_withouttls: 3201
  disc_h2_withouttls: 3202
  reg_h2_withouttls: 3002

  metrics_port: 3003

env:
  topicname: "nrfagent-nfprofile"
  topicpartitions: "'1'"
  topicreplication: "'1'"

resources:
  cpu: "500m"
  memory: "256Mi"
  maxCpu: "2000m"
  maxMemory: "1024Mi"

configmap:
  name: nrf-agent-targetnfprofiles
  mountpath: /etc/nrfagent/cm/configmap/
  nrfagent_conf: eric-nrfagent-config
  configmap_confile: /app/nrfagent/conf/

jsonschema:
  configmap:
    name: "eric-nrfagent-jsonschema"
    mountpath: "/etc/nrfagent/jsonschema/"
  nfProfileInSearchResult:
    fileName: "nfProfileInSearchResult.json"
  patchDocument:
    fileName: "patchDocument.json"

sidecar:
  image:
    name: nrfagent-sidecar
    tag: 1.0.0
    pullPolicy: Always
  label: nrf-agent-targetnfprofiles
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m

elector:
  image:
    name: nrf-leader-elector
    tag: 0.1
    pullPolicy: Always
  port: 4040
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
global:
  nf_instance_name: eric
  kafka_connection: eric-data-message-bus-kf:9092
  cm_uri_prefix: http://eric-cm-mediator:5003/cm/api/v1.1
  imageCredentials:
    repository: armdocker.rnd.ericsson.se/proj-ipworks
  serviceAccountName: nrfagent-service-account
